{
  "scene": "scenes/topdown/level_02.scene",
  "gameMode": "TopDown",
  "allowedCivilianCasualties": 3,
  "silverTime": 60,
  "goldTime": 55,
  "onyxTime": 50,
  "slowestTime": 180,
  "fastestTime": 60,
  "simulatedTime": 80,
  "friendlyLevelName": "Level 02",
  "friendlyLevelDescription": "Level 02 Description",
  "artworkImageData": null,
  "isLeaderboardLevel": true,
  "statNameOverride": null,
  "__references": [],
  "__version": 0
}